version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:80'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - MONGODB_URI=mongodb://host_machine_ip:27017/mydatabase
    depends_on:
      - mongodb
  mongodb:
    # No need to define MongoDB service if it's running outside Docker