on: 
  push:
    branches:
      - "main"
    paths:
      - "server/**"

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - name: "Build the Golang Docker image and start the container"
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST_DEPLOYEMENT_INSTANCE }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          ls -lhta "/home/dockerTest/"
          cd /home/dockerTest/ && git pull
          cd /home/dockerTest/ && git show -s
  
          COMPOSE_PROJECT_NAME="maharaja-backend"
          cd /home/dockerTest && docker compose rm -fsv backend
          cd /home/dockerTest && docker image ls -a
          cd /home/dockerTest && docker image rm dockertest-backend
          cd /home/dockerTest && docker compose up -d backend
